general:
  project_name: open-problems-multimodal
  seed: &seed 1
  cv: donor
  wandb_desabled: false
  # fold: [0, 1, 2, 3, 4] # list (0-idx start) or null. set one element list, hold-out mode.
  # n_splits: 5
  save_name: cite/lightgbm_dayss_fraction_seed1

task: cite
data_type: svd_important_laurent
svd_dim: 64
day_std_inputs: true
day_donor_std_inputs: false
day_std_targets: false
use_meta: null
gender: false

model: lgbm
lgbm_params:
  n_estimators: 100
  feature_fraction: 0.5
  random_state: *seed

model_save: true
