general:
  project_name: open-problems-multimodal
  seed: &seed 42
  cv: all
  wandb_desabled: true
  # fold: [0, 1, 2, 3, 4] # list (0-idx start) or null. set one element list, hold-out mode.
  # n_splits: 5
  save_name: multi/all/ridge_corr_10_dayss

task: multi
data_type: corr_10
svd_dim: 16
day_std_inputs: true
day_donor_std_inputs: false
day_std_targets: false
use_meta: null
gender: true

model: ridge
ridge_params:
  alpha: 1.0

model_save: true
