general:
  project_name: open-problems-multimodal
  seed: &seed 5
  cv: all
  wandb_desabled: true
  #fold: [0, 1, 2, 3, 4] # list (0-idx start) or null. set one element list, hold-out mode.
  #n_splits: 5
  save_name: multi/all/mlp_multi_e50_dayss_umap10_seed5

task: multi
data_type: umap10
svd_dim: 64
day_std_inputs: true
day_donor_std_inputs: false
day_std_targets: false
use_meta: null
gender: true

model: mlp
dropout: 0.0
batchnorm: true

model_save: &model_save true

pl_params:
  max_epochs: &max_epochs 50
  accelerator: auto
  accumulate_grad_batches: 1
  precision: 32 # 16 or 32
  deterministic: true
  benchmark: false
  enable_checkpointing: *model_save
  enable_model_summary: false
  enable_progress_bar: true
  #limit_train_batches: 0.1 # for debug
  #limit_val_batches: 0.1 # for debug

early_stopping: null
#  patience: 10

criterion: correl_loss #MSELoss
optimizer:
  name: AdamW
  params:
    lr: 1.0e-2
    weight_decay: 1.0e-2
scheduler:
  name: OneCycleLR
  params:
    pct_start: 0.1
    div_factor: 1.0e+3
    max_lr: 1.0e-2
    epochs: 50

train_loader:
  batch_size: 256
  shuffle: true
  num_workers: 2
  pin_memory: true
  drop_last: true
valid_loader:
  batch_size: 1024
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false
test_loader:
  batch_size: 1024
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false
